# Generated by Django 4.0 on 2021-12-19 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentlike',
            old_name='post',
            new_name='comment',
        ),
    ]
